export enum ActionType {
    INIT = 'INIT',
    SOCKET_CONNECT = 'SOCKET_CONNECT',
    SOCKET_ERROR = 'SOCKET_ERROR',
    SOCKET_MESSAGE = 'SOCKET_MESSAGE',
    WELCOME = 'WELCOME',
    CREATE_TUNNEL = 'CREATE_TUNNEL',
    REMOVE_TUNNEL = 'REMOVE_TUNNEL',
    SELECT = 'SELECT',
    REQUESTS = 'REQUESTS',
    REQUEST = 'REQUEST',
}